# Site
name: "Blog"
title: "BSafes Blog"
description: "Introducing BSafes Collaborative Note-Taking with 256-Bit End-to-End Encryption"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ''
bsafesURL: 'https://www.bsafes.com'
google_analytics: 'UA-46278016-1'
disqus: 'demowebsite'
mailchimp-list: 
include: ["_pages"]
permalink: /:title/
company: "Wu-Nan Technology Inc."

# Authors
authors:
  EJServiceKiosk:
    name: EJServiceKiosk 
    display_name: EJServiceKiosk
    avatar: https://statics.bsafes.com/images/megaphone-2374502_640.png 
    email: support@bsafes.com
    web: https://www.fiverr.com/ejservicekiosk?source=order_page_summary_seller_link
    twitter: 
    description: "I'm an Internet Culture expert"
  fahadkhan1990:
    name: fahadkhan1990 
    display_name: fahadkhan1990 
    avatar: https://fiverr-res.cloudinary.com/t_profile_original,q_auto,f_auto/attachments/profile/photo/92250c016d4dde599ba633399fa89c35-1524519092694/d24b9fb4-00d3-4758-96d4-15ed0f17c81a.jpg 
    email: support@bsafes.com
    web: https://www.fiverr.com/fahadkhan1990?source=order_page_summary_seller_link 
    twitter:
    description: "Hey, I am Fahad and I have done M.Phil in Computer Science. I am a tech geek and creative writer."
  legitjoe:
    name: legitjoe 
    display_name: legitjoe    
    avatar: 'https://fiverr-res.cloudinary.com/t_profile_original,q_auto,f_auto/attachments/profile/photo/f96fb561da939824558abc931a54f837-1566031871879/f1b0f76c-ce59-4cd5-9bff-c0cc13df051a.PNG'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: support@bsafes.com 
    web: https://www.fiverr.com/legitjoe 
    twitter: 
    description: "Expert Writer and editor, Offering Legit services everyday"
  malik_zeeshan:
    name: malik_zeeshan 
    display_name: malik_zeeshan
    avatar: 'https://fiverr-res.cloudinary.com/t_profile_original,q_auto,f_auto/profile/photos/20665010/original/1493325572264_Profile.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: support@bsafes.com
    web: https://www.fiverr.com/malik_zeeshan?source=order_page_summary_seller_link 
    twitter:
    description: "Certified Cyber-Security Professional with 5 years of Industry Experience with Multiple certifications in cyber security."
  mutunemunyaka:
    name: mutunemunyaka 
    display_name: mutunemunyaka 
    avatar: 'https://fiverr-res.cloudinary.com/t_profile_original,q_auto,f_auto/attachments/profile/photo/db10ba23c7303e60e2fc1fa7851a4e78-1522100756663/7e51161c-0e0f-4982-888f-b71ef9a0bcc3.jpg'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: support@bsafes.com
    web: https://www.fiverr.com/mutunemunyaka?source=order_page_summary_seller_link 
    twitter:
    description: "I'm your expert in cybesecurity and cloudcomputing projects and papers"
# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
